version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-meetuptravel}
      MYSQL_USER: ${MYSQL_USER:-meetupuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-meetuppassword}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - meetuptravel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-meetuptravel}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-meetupuser}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-meetuppassword}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      PORT: 8080
    networks:
      - meetuptravel-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - meetuptravel-network
    restart: unless-stopped
    environment:
      PORT: 80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  admin:
    build: ./frontend-admin
    ports:
      - "${ADMIN_PORT:-8081}:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - meetuptravel-network
    restart: unless-stopped
    environment:
      PORT: 80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  meetuptravel-network:
    driver: bridge

volumes:
  mysql-data: 